import { Produto, Vendedor } from "@/types/database";

export const MOCK_VENDEDORES: Vendedor[] = [
  {
    id: "vend-1",
    usuario_id: "user-v1",
    nome_loja: "Sítio Vista Linda — Queijaria & Orgânicos",
    descricao: "Produção familiar agroecológica de queijos artesanais curados e hortaliças frescas nas montanhas capixabas.",
    cidade: "Domingos Martins - ES",
    criado_em: "2026-08-01T10:00:00Z",
  },
  {
    id: "vend-2",
    usuario_id: "user-v2",
    nome_loja: "Apiário & Pomar Flor da Serra",
    descricao: "Méis puros silvestres, própolis verde e geleias artesanais sem conservantes químicos.",
    cidade: "Santa Teresa - ES",
    criado_em: "2026-08-05T14:30:00Z",
  },
  {
    id: "vend-3",
    usuario_id: "user-v3",
    nome_loja: "Ateliê Barro & Palha Artesanal",
    descricao: "Peças decorativas em cerâmica terracota e cestaria sustentável trançada à mão.",
    cidade: "Guarapari - ES",
    criado_em: "2026-08-10T09:15:00Z",
  },
  {
    id: "vend-4",
    usuario_id: "user-v4",
    nome_loja: "Padaria da Terra — Fermentação Natural",
    descricao: "Pães rústicos de fermentação lenta (levain), focaccias aromáticas e biscoitos caseiros.",
    cidade: "Vitória - ES",
    criado_em: "2026-08-12T11:00:00Z",
  }
];

export const MOCK_PRODUTOS: Produto[] = [
  {
    id: "prod-1",
    vendedor_id: "vend-1",
    nome: "Queijo Artesanal Meia Cura da Serra (500g)",
    descricao: "Produzido com leite cru de vacas criadas a pasto nas montanhas. Maturação de 30 dias com casca florida e textura macia.",
    preco: 38.50,
    categoria: "Queijos & Laticínios",
    estoque_qtd: 14,
    imagem_url: "https://images.unsplash.com/photo-1552767059-ce182ead6c1b?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-15T08:00:00Z",
    vendedor: MOCK_VENDEDORES[0],
  },
  {
    id: "prod-2",
    vendedor_id: "vend-2",
    nome: "Mel Puro de Flores Silvestres (500g)",
    descricao: "Mel 100% puro e cru colhido em florada nativa da Mata Atlântica. Rico em antioxidantes e sabor floral suave.",
    preco: 29.90,
    categoria: "Mel & Geleias",
    estoque_qtd: 22,
    imagem_url: "https://upload.wikimedia.org/wikipedia/commons/d/da/Small_Honey_Jar_with_Honeycomb_-_51330849013.jpg",
    ativo: true,
    criado_em: "2026-08-16T09:30:00Z",
    vendedor: MOCK_VENDEDORES[1],
  },
  {
    id: "prod-3",
    vendedor_id: "vend-4",
    nome: "Pão Rústico Levain Multigrãos",
    descricao: "Fermentação 100% natural de 36 horas com farinha orgânica, linhaça dourada, girassol e gergelim tostado.",
    preco: 22.00,
    categoria: "Panificação & Doces",
    estoque_qtd: 8,
    imagem_url: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-18T07:00:00Z",
    vendedor: MOCK_VENDEDORES[3],
  },
  {
    id: "prod-4",
    vendedor_id: "vend-1",
    nome: "Cesta de Hortaliças Orgânicas da Estação",
    descricao: "Alface crespa, rúcula, couve manteiga, cenouras baby, rabanete e cheiro-verde recém-colhidos no dia da entrega.",
    preco: 35.00,
    categoria: "Hortifrúti",
    estoque_qtd: 12,
    imagem_url: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-19T06:45:00Z",
    vendedor: MOCK_VENDEDORES[0],
  },
  {
    id: "prod-5",
    vendedor_id: "vend-3",
    nome: "Cesto Multiuso de Fibra Natural Trançada",
    descricao: "Feito à mão por artesãs locais com taboa e palha de milho tratada. Ideal para pães, frutas ou decoração afetiva.",
    preco: 54.00,
    categoria: "Artesanato",
    estoque_qtd: 6,
    imagem_url: "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-20T14:10:00Z",
    vendedor: MOCK_VENDEDORES[2],
  },
  {
    id: "prod-6",
    vendedor_id: "vend-2",
    nome: "Geleia Artesanal de Morango com Pimenta Rosa",
    descricao: "Morangos frescos das montanhas cozidos lentamente em tacho de cobre com toque aromático de pimenta rosa.",
    preco: 24.50,
    categoria: "Mel & Geleias",
    estoque_qtd: 15,
    imagem_url: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-21T10:20:00Z",
    vendedor: MOCK_VENDEDORES[1],
  },
  {
    id: "prod-7",
    vendedor_id: "vend-3",
    nome: "Caneca de Cerâmica Terracota Esmaltada (300ml)",
    descricao: "Modelada no torno com queima em alta temperatura (1240°C). Design ergonômico e acabamento rústico exclusivo.",
    preco: 42.00,
    categoria: "Artesanato",
    estoque_qtd: 9,
    imagem_url: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-22T16:00:00Z",
    vendedor: MOCK_VENDEDORES[2],
  },
  {
    id: "prod-8",
    vendedor_id: "vend-1",
    nome: "Café Especial Arábica Torrado em Grãos (250g)",
    descricao: "Café 100% arábica cultivado a 1.100m de altitude. Notas sensoriais de caramelo, chocolate e acidez cítrica equilibrada.",
    preco: 32.00,
    categoria: "Bebidas Artesanais",
    estoque_qtd: 20,
    imagem_url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=80",
    ativo: true,
    criado_em: "2026-08-23T08:30:00Z",
    vendedor: MOCK_VENDEDORES[0],
  }
];
